name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check code formatting/imports
        run: sbt "scalafixAll --check"
      - name: Run tests
        uses: ./.github/actions/run-tests-with-pg-tmp
        env:
          PG_TMP_CMD: '/pg_tmp.sh'
          DB_USER: 'postgres'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: target
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-jobs
